[build]
  publish = "client"
  functions = "server"

[functions]
  # This tells Netlify which files to zip up with your function
  included_files = ["server/views/**"]
  # This external_node_modules list ensures ejs is bundled correctly
  external_node_modules = ["ejs"]

[functions.index]
  # This targets your server/index.js specifically
  node_bundle = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
